travis:
  secure:
    BINSTAR_TOKEN: HrUdTBPFxvk8TwltbmR7EEbwBLCLhbv02lhLJElQj6aXBk5l0zaKQw6R8hsSZkSLP/RltAa+XQBoHeViXMved1SZemt2+Cl88ZzQ7D5gMv+BHh37wml6f3D9Upte/rlSD4t1LsVkNYRFOjElWIHLjdkVTnjCoITnGEQkpT5AZ9pqeJgAuhsRn80j54PXu6UotDZPXgB2R7kr/t47F+SHPh9CpcG0cI/3m62aMZ8f25bCm0dH+YqjIMWvCU8x4XTJ0EBK/wRvgTaX28O3cK7bFZceqwbhYmcQfE23epmCwFJRwKW0Wjqi42hUFX0xZz3PyFTWXBfVqjVBcNzHJFFyCp689stsg4ZP3tJXcnKpnVgUmOJpeaAy6FUqY2jaPv7pI5MhNo88kZlRTmXMICjTlda2B2/SHfOIw3ehe9dBMyOE+VwcJ1lP6UuQbuQhZfd9Mom72qZSXzuvhBcr196Rg1GJdBHj0xzrv4POH21ICEZK9pmJ//lOPUtQaXf0UzRGYNcsftC8geK9due2//ovnusmILawiChufH3KBIJ8am2nUcwW4ZMWuSuDuLNdw2NkF2kwordlAGm2Tcpvt7MRiJCFUiXNL2OkkyR7Vv+tioGG4h2nq4bixfxFrQH9Is9YW6hCM8uoKkUf+IJFukRN5d7z4D2krWzYzntwS82GRas=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
