travis:
  secure:
    BINSTAR_TOKEN: BDAPD2T1jXVSa9IBYu1d1tTHM1Q/g8te0jv0r0HiMO46OqWTOS9Er8McfLW/KXHnpFVy/+JmGYhZzhCS6d6SgIkMtLiZ94p1I/0khpOjm3ZWuPCy5bXHPiFN/BDpeMhBxhQadtByFbYJ6UE+snS3OkZLPPlmOX19FN8/3yRmUChegRWojK3aEupEORQ/XM20DLP18i/6f186h44bqoZ8mWQdem29lgu0SpGoi1DTHr5h7AZHM+blQcYeEFuWwiMuvT4+eVDw/De2qNilAzYLCv70gm03yYSSu00HVbNpbld3EXfR/YCICwn44g3+NWOhEjSn5MhovjLzrinhjb9lHpjFkb26FpON92xbzDRRm3lOoIxYYFKtJx8vh9qOXF2g1PxVYwR7pfxQ3rKikwnlPNlkQ8Y8bH/01uEyeIrMKDM3hUW1uxPfRvpzvnFShqMAiYOdnBEZ8fT+ilXWLWoLNS/qgQ87C+2BpKxsJoh2teTG7Tr5nQrISlWftf/1bXZVGaQfreDDRruhdkPCkf2zPA0TTdO8oREOiexueX5DySEbFBwpHl/odCEB4Om8z5TuKReCNCPVLnQNTze2c9iZBA/c/LJbbavXYFQdVNJFszXHqJyBBm+4E6RxrKf6wofkDx6YfhuNQcs2ThDf3/b/kRCKnpYTZFqJPx8UgTEMarI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
